package com.seckill.dao;

import com.seckill.dataobject.ItemDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jul 21 15:57:21 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jul 21 15:57:21 CST 2019
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jul 21 15:57:21 CST 2019
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jul 21 15:57:21 CST 2019
     */
    ItemDO selectByPrimaryKey(Integer id);

    /**
     * 查询所有记录，并根据销量降序排序
     * @return
     */
    List<ItemDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jul 21 15:57:21 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jul 21 15:57:21 CST 2019
     */
    int updateByPrimaryKey(ItemDO record);

    /**
     * 增加销量
     * @param id
     * @param amount
     * @return
     */
    int increaseSales(@Param("id") Integer id, @Param("amount") Integer amount);
}