package com.seckill.dataobject;

public class SequenceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.name
     *
     * @mbg.generated Mon Jul 22 09:40:32 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.curren_value
     *
     * @mbg.generated Mon Jul 22 09:40:32 CST 2019
     */
    private Integer currenValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.step
     *
     * @mbg.generated Mon Jul 22 09:40:32 CST 2019
     */
    private Integer step;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.name
     *
     * @return the value of sequence_info.name
     *
     * @mbg.generated Mon Jul 22 09:40:32 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.name
     *
     * @param name the value for sequence_info.name
     *
     * @mbg.generated Mon Jul 22 09:40:32 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.curren_value
     *
     * @return the value of sequence_info.curren_value
     *
     * @mbg.generated Mon Jul 22 09:40:32 CST 2019
     */
    public Integer getCurrenValue() {
        return currenValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.curren_value
     *
     * @param currenValue the value for sequence_info.curren_value
     *
     * @mbg.generated Mon Jul 22 09:40:32 CST 2019
     */
    public void setCurrenValue(Integer currenValue) {
        this.currenValue = currenValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.step
     *
     * @return the value of sequence_info.step
     *
     * @mbg.generated Mon Jul 22 09:40:32 CST 2019
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.step
     *
     * @param step the value for sequence_info.step
     *
     * @mbg.generated Mon Jul 22 09:40:32 CST 2019
     */
    public void setStep(Integer step) {
        this.step = step;
    }
}